//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATM_Table
    {
        public int ID { get; set; }
        public Nullable<int> Card_Number { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> Pin { get; set; }
    }
}
